- type: playTimeTracker
  id: JobAnomaly

- type: playTimeTracker
  id: JobInventorySpecialist
  
- type: playTimeTracker
  id: JobFreelancer
  
# - type: playTimeTracker
  # id: JobServiceQuadBorg

# - type: playTimeTracker
  # id: JobMedicalQuadBorg
