- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerWarden
        - !type:NestedSelector
          tableId: FillLockerWardenHarduit

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerWarden

- type: entityTable
  id: FillLockerWarden
  table: !type:AllSelector
    children:
    - id: FlashlightSeclite
#    - id: WeaponDisabler # Frontier
    - id: WeaponEnergyRevolver # HL
    - id: NFWeaponEnergySubMachineGunDisabler # HL
    - id: ClothingBeltSecurityFilled
    - id: Flash
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHandsGlovesCombat
    - id: ClothingShoesBootsJack
    - id: ClothingOuterCoatWarden
    - id: ClothingOuterWinterWarden
    - id: RubberStampWarden
    - id: DoorRemoteArmory
    - id: HoloprojectorSecurity
    - id: BookSpaceLaw
    - id: NetworkConfigurator
    - id: Binoculars
    - id: WeaponEnergyHalberdAntique # HL
    - !type:AllSelector
      rolls: !type:ConstantNumberSelector
        value: 2
      children:
      - id: ClothingBackpackElectropack
      - id: RemoteSignaller

- type: entityTable
  id: FillLockerWardenHarduit
  table: !type:AllSelector
    children:
    - id: ClothingOuterHardsuitWarden
#    - id: OxygenTankFilled
    - id: NFTankO2N2EqualFilled # Frontier
    - id: ClothingMaskBreath
    - id: JetpackSecurityFilled # Frontier
    - id: ClothingShoesBootsMagSecurityFilled # Frontier

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerSecurity

- type: entityTable
  id: FillLockerSecurity
  table: !type:AllSelector
    children:
    - id: FlashlightSeclite
      prob: 0.8
#    - id: WeaponDisabler # Frontier
    - id: WeaponEnergyRevolver # HL
    - id: NFWeaponEnergySubMachineGunDisabler # HL
    - id: ClothingUniformJumpsuitSecGrey
      prob: 0.3
    - id: ClothingHeadHelmetBasic
    - id: ClothingOuterArmorPlate
    - id: ClothingBeltSecurityFilled
    - id: Flash
      prob: 0.5
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHeadsetSecurity
    - id: ClothingHandsGlovesColorBlack
    - id: ClothingShoesBootsJack
    - id: WeaponMeleeNeedle
      prob: 0.1
    - id: HoloprojectorSecurity
      prob: 0.6
    - id: BookSpaceLaw
      prob: 0.5

- type: entity
  id: LockerBrigmedicFilled
  suffix: Brigmedic, Filled
  parent: LockerBrigmedic
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerBrigmedic

- type: entityTable
  id: FillLockerBrigmedic
  table: !type:AllSelector
    children:
    - id: ClothingEyesGlassesSecurity
#    - id: WeaponDisabler # Frontier
    - id: WeaponEnergyRevolver # HL
    - id: NFWeaponEnergySubMachineGunDisabler # HL
    - id: TrackingImplanter
    - id: TrackingImplanter
#    - id: ClothingOuterHardsuitBrigmedic # HL: Moved to HLFillHardsuitBrigmedic
    - id: BoxSterileMask
    - id: ClothingHeadHatBeretBrigmedic
    - id: ClothingOuterCoatAMG
    - id: ClothingUniformJumpsuitBrigmedic
    - id: ClothingUniformJumpskirtBrigmedic
    - id: ClothingUniformJumpskirtOfLife
      prob: 0.1
    - id: MedkitFilled
    - !type:GroupSelector
      prob: 0.7
      children:
      - id: MedkitCombatFilled
        weight: 1.6
      - id: MedkitAdvancedFilled
      - id: MedkitOxygenFilled
        weight: 0.8
      - id: MedkitBruteFilled
        weight: 0.8
      - id: MedkitToxinFilled
        weight: 0.8
      - id: MedkitBurnFilled
        weight: 1.8
    - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
      prob: 0.15

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerDetective

- type: entityTable
  id: FillLockerDetective
  table: !type:AllSelector
    children:
    - id: ClothingEyesGlassesSecurity
      prob: 0.3
    - id: ClothingHeadHatDetGadget
    - id: ClothingNeckTieDet
    - id: ClothingOuterVestDetective
    - id: ClothingOuterCoatDetectiveLoadout
    - id: FlippoEngravedLighter
    - id: FlashlightSeclite
    - id: ForensicScanner
    - id: LogProbeCartridge
    - id: BoxForensicPad
    - id: DrinkDetFlask
    - id: ClothingHandsGlovesForensic
    - id: RubberStampDetective
    - id: HoloprojectorSecurity
    - id: BoxEvidenceMarkers
    - id: HandLabeler
    - id: BoxTapeRecorder # DeltaV
      prob: 0.3

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      - id: Wirecutter
      - id: Screwdriver
      - id: Multitool
        prob: 0.5

- type: entity
  parent: [GunSafeBaseSecure, BaseC1Contraband ] # Frontier: BaseSecurityContraband<BaseC1Contraband
  id: GunSafeDisabler
  name: disabler safe
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeDisabler

- type: entityTable
  id: FillGunSafeDisabler
  table: !type:AllSelector
    rolls: !type:ConstantNumberSelector
      value: 5
    children:
    - id: NFWeaponEnergySubMachineGunDisabler # HL
    

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafePistolMk58
  name: mk58 safe
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafePistolMk58

- type: entityTable
  id: FillGunSafePistolMk58
  table: !type:AllSelector
    rolls: !type:ConstantNumberSelector
      value: 4
    children:
    - id: WeaponPistolMk58
    - id: Magazine45_ACPPistolFMJ #HL
    - id: Magazine45_ACPPistolFMJ #HL

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafeRifleLecter
  name: Lecter safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRifleLecter

- type: entityTable
  id: FillGunSafeRifleLecter
  table: !type:AllSelector
    rolls: !type:ConstantNumberSelector
      value: 2
    children:
    - id: WeaponRifleLecter
    - id: Magazine556x45mmFMJ # HL
    - id: Magazine556x45mmFMJ # HL

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafeSubMachineGunDrozd
  name: Drozd safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeSubMachineGunDrozd

- type: entityTable
  id: FillGunSafeSubMachineGunDrozd
  table: !type:AllSelector
    rolls: !type:ConstantNumberSelector
      value: 2
    children:
    - id: NFWeaponSubMachineGunDrozd # Frontier: WeaponSubMachineGunDrozd<NFWeaponSubMachineGunDrozd
    - id: Magazine9x19mmSubMachineGunFMJ # HL
    - id: Magazine9x19mmSubMachineGunFMJ # HL

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafeShotgunEnforcer
  name: Enforcer safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeShotgunEnforcer

- type: entityTable
  id: FillGunSafeShotgunEnforcer
  table: !type:AllSelector
    rolls: !type:ConstantNumberSelector
      value: 2
    children:
    - id: NFWeaponShotgunEnforcer # Frontier: WeaponShotgunEnforcer<NFWeaponShotgunEnforcer
    - id: AmmoBox12_gaugeBuckshot #HL
    - id: AmmoBox12_gaugeBuckshot #HL

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafeShotgunKammerer
  name: Kammerer safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeShotgunKammerer

- type: entityTable
  id: FillGunSafeShotgunKammerer
  table: !type:AllSelector
    rolls: !type:ConstantNumberSelector
      value: 2
    children:
    - id: NFWeaponShotgunKammerer # Frontier: WeaponShotgunKammerer<NFWeaponShotgunKammerer
    - id: AmmoBox12_gaugeBuckshot # HL

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  name: WT-550 safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeSubMachineGunWt550

- type: entityTable
  id: FillGunSafeSubMachineGunWt550
  table: !type:AllSelector
    rolls: !type:ConstantNumberSelector
      value: 2
    children:
    - id: NFWeaponSubMachineGunWt550 # Frontier: WeaponSubMachineGunWt550<NFWeaponSubMachineGunWt550
    - id: Magazine46x30mmSubMachineGunTopMountedFMJ #HL
    - id: Magazine46x30mmSubMachineGunTopMountedFMJ #HL

- type: entity
  parent: [GunSafeBaseSecure] # Frontier: remove BaseSecurityContraband
  id: GunSafeLaserCarbine
  name: laser safe
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeLaserCarbine

- type: entityTable
  id: FillGunSafeLaserCarbine
  table: !type:AllSelector
    rolls: !type:ConstantNumberSelector
      value: 3
    children:
    - id: NFWeaponEnergyRifleCarbine # Frontier: WeaponLaserCarbine<NFWeaponEnergyRifleCarbine
