- type: playTimeTracker
  id: JobServiceQuadBorg

- type: playTimeTracker
  id: JobMedicalQuadBorg

- type: playTimeTracker
  id: JobSecurityQuadBorg

- type: playTimeTracker
  id: JobEngineeringQuadBorg

- type: playTimeTracker
  id: JobSalvageQuadBorg